# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de02837bc3e1ccbf5ce5dced8d35ef93d73bbf37b6c3f42b090fbca90239c71ebb40c41d6bce4fac2539b4f73ea99c08951f9b32738d0bf4fc9e67a27bd15ce6

test:
  secret_key_base: dfa2a699036f33ccde5d3879181a37b08179463bce8ead99fee326eeb33458d5373ea4f92dddc4ce2b365f3ccabac3a696e9badbf4bc36db11a5f4b0a8a0c8d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
